<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AdyenBridge.Contracts\AdyenBridge.Contracts.csproj" />
    <ProjectReference Include="..\AdyenBridge.Application\AdyenBridge.Application.csproj" />
    <ProjectReference Include="..\AdyenBridge.Infrastructure\AdyenBridge.Infrastructure.csproj" />
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" OutputItemType="Analyzer" />
  </ItemGroup>
</Project>

